#プラグインのチャットプレフィクス
plugin-prefix: " &2>&a>&r "

#各ログのメッセージ

#プレースホルダ
# {WORLD}: ワールド名
# {PLAYER}: プレイヤー名
# {DISPLAYNAME}: プレイヤーの表示名
# {UUID}: プレイヤーUUID
# {X}: X座標
# {Y}: Y座標
# {Z}: Z座標
# {COMMAND}: 実行コマンド
cmdlog-player: " §a* §7{PLAYER} : {COMMAND}"
cmdlog-console: " §a* §7CONSOLE : {COMMAND}"
cmdlog-rcon: " §a* §7RCON : {COMMAND}"
cmdlog-cmdblock: " §a* §7CMDBLOCK : {COMMAND} [{WORLD} - X: {X} Y: {Y} Z: {Z}]"

#各ログ有効にするか
enable-player: true
enable-console: true
enable-rcon: true
enable-cmdblock: true